---
title: "RNA Sequencing - Oyesters"
output: html_notebook
---

Load the needed packages

```{r}
suppressPackageStartupMessages({
    library(AnnotationDbi)
    library(org.Mm.eg.db)
    library(hgu95av2.db)
    library(SummarizedExperiment)
})
```

Set Working Directory

```{r}
setwd("/work/clh162/Data+/Arushi/2025-2026-team-code/Data+_team/Arushi")
```

Check Files within the directory

```{r}
list.files("../multiqc_report_raw/multiqc_data")
list.files("../multiqc_report_trimmed/multiqc_data")
```

Open these files

```{r}
browseURL("../multiqc_report_trimmed/multiqc_report.html")
```

Read Data

```{r}
raw_fastqc <- read.delim(
  "../multiqc_report_raw/multiqc_data/multiqc_fastqc.txt",
  check.names = FALSE
)

trimmed_fastqc <- read.delim(
  "../multiqc_report_trimmed/multiqc_data/multiqc_fastqc.txt",
  check.names = FALSE
)

dim(raw_fastqc)
dim(trimmed_fastqc)

head(raw_fastqc)
head(trimmed_fastqc)

```

Count Check Matrix

```{r}
count_dir <- "/work/clh162/OysterRNA24/hisat2_align/featureCounts_counts"

files <- list.files(
  count_dir,
  pattern = "_gene_counts\\.txt$",
  full.names = TRUE
)

length(files)
basename(files)[1:5]

test <- read.delim(files[1], comment.char = "#", check.names = FALSE)

dim(test)
names(test)
head(test)
```

```{r}
count_dir <- "/work/clh162/OysterRNA24/hisat2_align/featureCounts_counts"

files <- list.files(
  count_dir,
  pattern = "_gene_counts\\.txt$",
  full.names = TRUE
)

read_featurecounts <- function(file) {
  df <- read.delim(
    file,
    comment.char = "#",
    check.names = FALSE
  )
  
  sample_name <- basename(file)
  sample_name <- sub("_gene_counts\\.txt$", "", sample_name)
  
  gene_col <- 1
  count_col <- ncol(df)
  
  counts <- df[, c(gene_col, count_col)]
  names(counts) <- c("Geneid", sample_name)
  
  return(counts)
}

count_list <- lapply(files, read_featurecounts)

counts_df <- Reduce(
  function(x, y) merge(x, y, by = "Geneid", all = TRUE),
  count_list
)

rownames(counts_df) <- counts_df$Geneid
counts <- counts_df[, -1]

dim(counts)
head(counts[, 1:5])
```

```{r}
# Check for missing values
sum(is.na(counts))

# Check data type
str(counts[, 1:3])

# Summary of library sizes
summary(colSums(counts))

# How many genes have zero counts across all samples?
sum(rowSums(counts) == 0)

# How many genes have at least 10 counts total?
sum(rowSums(counts) >= 10)
```

Save Count Matrix for later

```{r}
write.csv(
  counts,
  "combined_featureCounts_gene_counts.csv",
  quote = FALSE
)
```

Sample Annotations

```{r}
library(readxl)

coldata <- read_excel("../xRNA for BC Summer 2024.xlsx")

dim(coldata)
head(coldata)
names(coldata)
```

Gene Annotation

```{r}
table(gtf$feature)
head(gtf$attribute, 10)
head(rownames(counts), 10)
```

```{r}
gtf$gene_id <- sub('.*gene_id "([^"]+)".*', '\\1', gtf$attribute)

# If gene_id was not found, this will leave the whole attribute string unchanged.
# So keep only rows where the regex actually worked:
gtf_gene_annot <- gtf[gtf$gene_id != gtf$attribute, ]

dim(gtf_gene_annot)
head(gtf_gene_annot[, c("gene_id", "seqname", "start", "end", "strand", "feature", "attribute")])
```

```{r}
rowranges <- gtf_gene_annot[!duplicated(gtf_gene_annot$gene_id), 
                            c("gene_id", "seqname", "start", "end", "strand", "feature", "attribute")]

rownames(rowranges) <- rowranges$gene_id

sum(rownames(counts) %in% rownames(rowranges))
length(rownames(counts))

rowranges <- rowranges[rownames(counts), ]

dim(rowranges)
head(rowranges)
all(rownames(rowranges) == rownames(counts))
```

```{r}
all(rownames(rowranges) == rownames(counts))

head(rownames(counts))
head(rownames(rowranges))
```
